Merge the Cadence and Synopsys plugins into Hammer
ucb-bar/hammer pull request #713
Opened 2023-03-02 03:29 UTC by vighneshiyer

I copied over the files from the Cadence and Synopsys plugin repos into hammer. There should be no functional changes. Running the e2e tests with the Cadence flow is still pending. Do we believe the Synopsys flow still works out-of-the-box?

2023-03-02 03:45 UTC, harrisonliew requested changes
Let's not include Synopsys DC & ICC. These plugins are too old/not maintained (erase them from the git history too).

2023-03-02 03:45 UTC, harrisonliew commented on .gitmodules
>  	branch = packaging
Can you point this to master instead?

2023-03-02 03:45 UTC, harrisonliew commented on hammer/drc/icv/README.md
> +# DRC/LVS with IC Validator
Can you include this into readthedocs like was done here: https://github.com/ucb-bar/hammer/blob/master/doc/CAD-Tools/OpenROAD.rst?

2023-03-14 00:03 UTC, vighneshiyer commented
I've squashed my commits and removed the DC/ICC plugins - let me know if there's anything else you'd like to fix. I still need to try the e2e tests.

2023-03-14 05:13 UTC, harrisonliew approved these changes
Looks good, pending e2e testing.

2023-03-14 20:00 UTC, harrisonliew requested changes

2023-03-14 20:00 UTC, harrisonliew commented on doc/CAD-Tools/ICV.md
Actually, this needs to be added to `doc/CAD-Tools/index.rst`.

2023-03-14 20:02 UTC, harrisonliew requested changes

2023-03-14 20:02 UTC, harrisonliew commented on hammer/synthesis/genus/__init__.py
Can you incorporate these two new commits to Genus? (1)[https://github.com/ucb-bar/hammer-cadence-plugins/commit/777e28a61fa248deb2dd6a285e7ca4f9bf39a7c4] and (2)[https://github.com/ucb-bar/hammer-cadence-plugins/commit/902657b8bdba7aec12726d6d3c85a2639a4030ad]

2023-03-15 00:50 UTC, harrisonliew approved these changes
Approving again, pending the other e2e test combos.

2023-03-16 22:48 UTC, vighneshiyer commented
I've tested RTL->GDS in e2e using Cadence tools using sky130 on the A machines. There is an issue with post-syn and post-par simulation where the dff stdcell doesn't appear to update on the rising clock edge, but I suspect this is an issue with the PDK's verilog models and not related to this PR. We can merge this unless there's something else you'd like to check.

2023-03-16 23:40 UTC, harrisonliew commented
All relevant issues from hammer-cadence-plugins and hammer-synopsys-plugins have been transferred over now.

2023-03-17 18:42 UTC, vighneshiyer commented
Everything looks good to go - you can look over the diff one more time and if it looks good, we can merge.

2023-03-20 21:33 UTC, harrisonliew commented
I had to cherry-pick [this commit](https://github.com/ucb-bar/hammer-synopsys-plugins/commit/e53fa5c51f37937c83df3b004693552f59015c90) and update sky130 bwrc keys.

2023-03-20 22:25 UTC, merged