Refactor e2e & Joules Plugin
ucb-bar/hammer pull request #799
Opened 2023-09-27 18:53 UTC by nayiri-k

This PR adds many more capabilities to the e2e tests, so that we can easily run flows for different designs/pdks/tools. The e2e/README summarizes how to run this flow. The PR also adds several features to the Cadence Joules power plugin, including writing database checkpoints between power steps, and supporting several reporting output formats (notably power profile instead of average power reporting).

**Related PRs / Issues**

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [ ] Change to core Hammer
- [ ] Change to a Hammer plugin
- [ ] Other

**Contributor Checklist**:
- [ ] Did you set `master` as the base branch?
- [ ] Did you state the type-of-change/impact?
- [ ] Did you delete any extraneous prints/debugging code?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you update the `poetry.lock` file if you updated the requirements in `pyproject.toml`?
- [ ] (If applicable) Did you add a unit test demonstrating the PR?
- [ ] (If applicable) Did you run this through the e2e integration tests?
- [ ] (If applicable) Did you update the submodules in `e2e/` if this feature depends on updated plugins?

2023-09-27 22:06 UTC, harrisonliew requested changes
Looks great! Some global comments:
 

1. With these updates to the README, I think we can directly include it into the readthedocs (instead of reference). See this folder for an example for how to symlink the Markdown file: https://github.com/ucb-bar/hammer/tree/master/doc/Technology.
2. `test` seems like it should be called `pass`? Perhaps this directory should actually be using the `nop` tools and techs so that it can truly be used for testing w/o any plugin dependencies. Then the power ymls should apply to GCD instead.

2023-09-28 18:12 UTC, harrisonliew commented on hammer/power/joules/defaults.yml
> +  version: "211"
Can you try using 22.1? It is also now merged under DDI (like #798)

2023-09-29 20:48 UTC, dpgrubb13 commented on e2e/configs-design/gcd/sky130.yml
> -
Can you add timing constraints for the GCD module here?

2023-09-29 20:51 UTC, dpgrubb13 commented on e2e/configs-design/gcd/asap7.yml
> +
Also add timing constraints on the I/O here.

2023-09-29 21:14 UTC, nayiri-k commented on e2e/configs-design/gcd/sim-par.yml
> +  timing_annotated: false
This was copied from the previous `e2e` files. Just changed to `true` & tested.

2023-10-02 16:56 UTC, harrisonliew approved these changes

2023-10-02 17:06 UTC, dpgrubb13 commented on e2e/configs-design/gcd/common.yml
> +# Generate Make include to aid in tlow
Follow up on the flow nit here.

2023-10-02 17:08 UTC, dpgrubb13 commented on e2e/configs-design/pass/joules.yml
>  power.inputs.waveforms: ["path/to/waveforem"]
Nit: waveform

2023-10-02 17:12 UTC, dpgrubb13 approved these changes
Just change the few nits. Looks great!

2023-10-02 18:02 UTC, merged