Improvements to supplies API
ucb-bar/hammer pull request #816
Opened 2023-11-03 23:38 UTC by jerryz123

- Change `vlsi.inputs.supplies.power/ground.pin` to `.pins`. This generates CPFs with a `create_global_connection` from  single net to multiple pins
- Add `power_straps_options.by_tracks.power_nets` setting. This controls which supply nets power straps are generated for. The default uses all supplies, but this is not always desired
- Add `vlsi.input.supplies.power.voltage` field. The existing system would always create the power_nets with the same `vlsi.inputs.supplies.VDD` voltage. This enables per-supply voltage setting.

**Related PRs / Issues**

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [ ] Change to core Hammer
- [ ] Change to a Hammer plugin
- [ ] Other

**Contributor Checklist**:
- [ ] Did you set `master` as the base branch?
- [ ] Did you state the type-of-change/impact?
- [ ] Did you delete any extraneous prints/debugging code?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you update the `poetry.lock` file if you updated the requirements in `pyproject.toml`?
- [ ] (If applicable) Did you add a unit test demonstrating the PR?
- [ ] (If applicable) Did you run this through the e2e integration tests?
- [ ] (If applicable) Did you update the submodules in `e2e/` if this feature depends on updated plugins?

2023-11-03 23:54 UTC, harrisonliew requested changes

2023-11-03 23:54 UTC, harrisonliew commented on hammer/config/defaults.yml
Can you also change the documentation for `pin`?
I'd like for this to still be `Optional[List[str]]`. Default behaviour if not specified should be that it would connect to pins matching the net name only.

2023-11-03 23:58 UTC, jerryz123 commented on hammer/config/defaults.yml
So the behavior should be 
 - None -> connect to pins matching the net name
 - Empty list -> connect to nothing
 - List -> connect to pins named in the list?

2023-11-04 00:00 UTC, harrisonliew commented on hammer/config/defaults.yml
Yes, that's perfect

2023-11-05 20:28 UTC, jerryz123 commented on hammer/config/defaults.yml
Done, can you check the UPF spec gen? I'm not sure I did the right thing here.

2023-11-05 22:13 UTC, harrisonliew approved these changes

2023-11-05 22:13 UTC, merged