support for mesh powerstrap
ucb-bar/hammer pull request #845
Opened 2024-03-06 09:49 UTC by yolowiz

**Related PRs / Issues**

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [x] Change to core Hammer
- [ ] Change to a Hammer plugin
- [ ] Other

**Contributor Checklist**:
- [x] Did you set `master` as the base branch?
- [x] Did you state the type-of-change/impact?
- [x] Did you delete any extraneous prints/debugging code?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you update the `poetry.lock` file if you updated the requirements in `pyproject.toml`?
- [x] (If applicable) Did you add a unit test demonstrating the PR?
- [ ] (If applicable) Did you run this through the e2e integration tests?
- [ ] (If applicable) Did you update the submodules in `e2e/` if this feature depends on updated plugins?

2024-03-06 17:58 UTC, harrisonliew requested changes
Can you update the documentation with a diagram using this new method? I'd like to see whether the utilization property makes sense (recommend 0.2 for diagram).

2024-04-01 17:35 UTC, harrisonliew commented on doc/Hammer-Use/mesh.png
I'm confused about this picture. Isn't only the bottom half actually the "mesh" method? The top half is existing "coupled" with track_spacing = 1.

2024-04-01 17:44 UTC, yolowiz commented on doc/Hammer-Use/mesh.png
It's an illustration of how twt is used.

2024-04-01 18:01 UTC, harrisonliew commented on doc/Hammer-Use/mesh.png
In my opinion, that is unnecessary (you can just overlay measurement e in the bottom half).

If anything, the existing diagrams above this should indicate the differences in calculation between twwt and twt when track_spacing = 0 or > 0.

2024-04-04 16:52 UTC, harrisonliew commented on doc/Hammer-Use/mesh_description.png
Much better. But isn't there a slight error for mesh straps? If it's 50% utilization, we should see:
 VDD | signal | VSS | signal | VDD | signal ...
Right now there are 2 signals between each power => 33% utilization

2024-04-04 17:16 UTC, yolowiz commented on doc/Hammer-Use/mesh_description.png
That arises from the fact that power utilization is not exact for power strap calculation: track_spacing is part of the consumed_tracks, and for mesh, track_spacing is hard-coded to 1.

2024-04-04 17:17 UTC, harrisonliew commented on doc/Hammer-Use/mesh_description.png
Oh, this is your hack to force twt calculation, right? can you force that calculation without needing to account for the extra spacing?

2024-04-04 17:29 UTC, yolowiz commented on doc/Hammer-Use/mesh_description.png
To keep the power utilization consistent with twt, yes. I can try to subtract the track_spacing after twt returns the width and spacing.

2024-04-04 18:32 UTC, harrisonliew commented on doc/Hammer-Use/mesh_description.png
Yes, please subtract that extra track_spacing in mesh mode so that the calculation is intuitive.

2024-04-11 18:14 UTC, harrisonliew approved these changes

2024-04-11 18:15 UTC, merged